- name: nginx install and run
  hosts: web
  become: yes # -b (Sudo permission)
  tasks:
  - name: nginx install
    ansible.builtin.package:
      name: nginx
      state: present
   - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started